version: '3.8'

services:
  api:
    container_name: django-drf-api
    build: .
    volumes:
      - .:/api
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ENGINE=${ENGINE}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=db
    command: bash -c "python manage.py makemigrations && python manage.py migrate && gunicorn crudproject.wsgi --bind 0.0.0.0:8000"
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: django-drf-db
    image: postgres:14.0-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 30s
      retries: 5
    environment:
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}