# Generated by Django 4.0 on 2021-12-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_car_avg_rating_car_rates_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='car',
            unique_together={('make', 'model')},
        ),
    ]
