name: Django CI

on:
  push:
  pull_request:
    branches: 
      - develop
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out
        uses: actions/checkout@v2
      - name: Docker Compose Up
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
          POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: docker-compose up -d
      - name: Run Tests
        run: docker exec django-drf-api python manage.py test